# -*- coding: utf-8 -*-
"""Segundo análisis de casos Gabriel Arroyo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3KTiDOj8r0dWkN3PkVHAhZlSr4xcgXo

# Tarea Semana 4: Segundo Análisis de Casos
## Código Limpio, Datos de Texto y Validación

### Objetivo
Resolver cuatro ejercicios fundamentales aplicando entrada de datos, limpieza de texto, conversión de tipos, condicionales y salidas claras con f-strings.

Cada ejercicio debe demostrar el razonamiento antes del código. No se trata solo de que el programa funcione: debe verse claramente qué datos entran, qué proceso se aplica y qué salida se espera.

## Formato obligatorio para cada ejercicio

Complete las siguientes partes:

1. **Problema:** describa qué debe resolver el programa.
2. **Entrada:** indique qué datos solicita al usuario.
3. **Proceso:** explique la fórmula, condición o validación usada.
4. **Salida esperada:** describa qué mensaje debe mostrar.
5. **Código:** escriba y ejecute la solución.
6. **Pruebas:** documente tres escenarios:
   - Caso normal.
   - Caso límite.
   - Caso inválido.

### Entrega

- Entregue este notebook `.ipynb` completo.
- Exporte también el trabajo a PDF.
- Como práctica opcional, entregue uno de los ejercicios adicionalmente como archivo `.py`.

## Ejercicios obligatorios

| # | Ejercicio | Descripción | Habilidades clave |
|---|-----------|-------------|-------------------|
| 1 | Calculadora de propina inteligente | Solicita total de cuenta y porcentaje de propina. Calcula propina y total final. | `float`, operaciones, f-strings |
| 2 | Detector de número par/impar | Solicita un entero e indica si es par o impar. | `int`, `%`, `if/else` |
| 3 | Clasificador de edad | Solicita edad y clasifica como menor, adulto o adulto mayor. | `int`, `if/elif/else` |
| 4 | Validador de compra con descuento | Solicita cliente, monto y si es cliente frecuente. Aplica descuento según reglas. | strings, `float`, `and/or`, f-strings |

Use `try-except` en los ejercicios donde el usuario deba ingresar números.

---
# Problema #1: Calculadora de propina inteligente

## Problema

Solicitud a usuarios que ingresen el total de cuenta más el porcentaje de propina que quieren incluir, calculando el dicho porcentaje más el total final.

## Entrada

- Ingrese el Total de cuenta:
- Ingrese el Porcentaje de propina:

## Proceso

- Propina = Total de cuenta * Porcentaje de propina / 100
- Total final = Total de cuenta + Propina

## Salida esperada

- Tu aporte fue de: Propina
- Tu monto final a cancelar es de: Total final

## Pruebas manuales

| Escenario | Datos de entrada | Resultado esperado | Resultado obtenido |
|-----------|------------------|--------------------|--------------------|
| Caso normal | 1000 y 50 respectivamente| 500 y 1500| 500 y 1500 |
| Caso límite | 1000 y 0 respectivamente | 0 y 1000| 0 y 1000|
| Caso inválido | 1000 y -1 respectivamente| Error| Error |
"""

total_cuenta = float(input('Ingrese el total de cuenta: '))
propina = float(input('Ingrese el porcentaje de propina: '))
porcentaje_propina = total_cuenta * propina / 100
total_final = total_cuenta + porcentaje_propina
if total_cuenta <= -1 or propina <= -1:
    print('Error: el monto debe ser mayor a -1')
else:
    print(f'Tu aporte fue de: {porcentaje_propina}')
    print(f'Tu monto final a cancelar es: {total_final}')

"""---
# Problema #2: Detector de número par/impar

## Problema

Programa encargado de identificar si un número es par o impar

## Entrada

- Ingrese un número entero:

## Proceso

- número % 2 == 0

## Salida esperada

- El número {} es un número par
- El número {} es un número impar

## Pruebas manuales

| Escenario | Datos de entrada | Resultado esperado | Resultado obtenido |
|-----------|------------------|--------------------|--------------------|
| Caso normal | 1| Número impar | Número impar |
| Caso límite | 0|Número par | Número par|
| Caso inválido |1.5 |Error |Error |

"""

try:
    numero = int(input('Ingrese un número entero: '))
    if numero % 2 == 0:
        print(f'El número {numero} es un número par')
    else:
        print(f'El número {numero} es un número impar')
except ValueError:
    print('ERROR: Dato inválido')

"""---
# Problema #3: Clasificador de edad

## Problema

Clasificar la etapa de una persona partiendo por su edad

## Entrada

- ¿Cuántos años tienes?

## Proceso

- edad <= 17 and edad > 0
- edad >= 18 and edad <= 64
- edad >= 65 and edad <= 120

## Salida esperada

- Tienes {edad} años. Eres menor de edad!
- Tienes {edad} años. Eres todo un adulto!
- Tienes {edad} años. Eres un adulto mayor!
- Error: dato inválido

## Pruebas manuales

| Escenario | Datos de entrada | Resultado esperado | Resultado obtenido |
|-----------|------------------|--------------------|--------------------|
| Caso normal | 28| Eres todo un adulto!| Eres todo un adulto!|
| Caso límite | 17| Eres menor de edad!| Eres menor de edad!|
| Caso inválido |0 |Error | Error|

"""

edad = int(input('¿Cuántos años tienes?: '))
if edad <= 17 and edad > 0:
    print(f'Tienes {edad} años. Eres menor de edad!')
elif edad >= 18 and edad <=64:
    print(f'Tienes {edad} años. Eres todo un adulto!')
elif edad >= 65 and edad < 120:
    print(f'Tienes {edad} años. Eres un adulto mayor!')
else:
    print('Error: dato inválido')

"""---
# Problema #4: Validador de compra con descuento

## Problema

Validación de compras que solicite el nombre del cliente, el monto de compra y si es cliente frecuente; y a partir de la información brindada, ofrecer o no un descuento.

## Entrada

- Nombre de cliente:
- Monto de compra:
- Frecuencia:

## Proceso

- Si el monto es menor a 0, da error
- Si no se agregan datos correctos, da error
- Si se agregan datos correctamente:
- Si monto es mayor a 2000 y frecuencia es sí: descuento de 30%
- Si monto es mayor a 2000 pero frecuencia es no: descuento de 20%
- Si monto es menor o igual a 2000 y frecuencia es sí: descuento 20%
- Si monto es menor o igual a 2000 pero frecuencia es no: no hay descuento

## Salida esperada

- Nombre
- Monto original
- Frecuencia
- Descuento
- Monto final

## Pruebas manuales

| Escenario | Datos de entrada | Resultado esperado | Resultado obtenido |
|-----------|------------------|--------------------|--------------------|
| Caso normal | Gabriel 5000 si|descuento de 30% y monto final de 3500 |descuento de 1500 y monto final de 3500 |
| Caso límite | Gabriel 2001 si|descuento de 30% y monto final 1400.7 | descuento de 600.3 y monto final de 1400.7|
| Caso inválido |Gabriel -1 no| Error pero fluye| Error pero crasheó|

"""

try:
    cliente = input('Nombre de cliente: ').strip().upper()
    monto = float(input('Monto de compra: '))
    frecuencia = input('Eres cliente frecuente? (si/no): ').lower().strip()

    if monto < 0:
        print('Error: monto de compra inválido')
    else:
        if monto > 2000 and frecuencia == 'si':
            descuento = monto * 0.3
        elif monto > 2000 and frecuencia == 'no':
            descuento = monto * 0.2
        elif monto <= 2000 and frecuencia == 'si':
            descuento = monto * 0.2
        else:
            descuento = 0
        monto_final = monto - descuento

    print('Nombre: ', cliente)
    print(f'Monto: {monto}')
    print('Frecuencia: ',frecuencia)
    print('Tu descuento es de: ',descuento)
    print('Monto final: ',monto_final)

except ValueError:
    print('Error: datos inválidos')

"""---
# Conclusión

Redacte una reflexión breve:

- ¿Qué validación le resultó más importante?

R/: En mi experiencia realizando este ejercicio, los comandos "try" y "except" me parecen muy útiles para asegurar eficacia del código. Dentro de las validaciones, el último ejercicio es el que más me tomó trabajo pero al mismo tiempo más me dio batalla para comprender los comandos, y esa validación más importante fue la del monto negativo.

- ¿Qué error encontró durante las pruebas?

R/: Un error que estuve cometiendo a la hora de escribir los códigos, era los espacios. Creo que al estar acostumbrado a escribir textos me apego a la idea de escribir "pegado a la izquierda"; pero en programación esto puede ocasionar un "crasheo". Básicamente, respetar los bloques anidados y comprender cuándo un proceso es parte de otro.

- ¿Cómo mejoró la limpieza del código la calidad del programa?

R/: Mejoró en la claridad y en la legibilidad. Permite que haya una comprensión más clara y precisa de los datos agregados.

"""

